### ISSUE TITLE
ruby flip not properly indented when using Pseudo functions

### ISSUE THREAD

**Issue by mvanholsteijn** [binxio/serverless-cfnflip#1]
![image](https://user-images.githubusercontent.com/576619/40408830-23a7830a-5e69-11e8-9e9d-97120f0150ba.png)

**Comment by dennisvink** [comment]
cfn2dsl attempts to pretty print the generated Ruby code and does a mediocre job. I'll see if I can improve indentation in a future release either by monkey patching cfn2dsl or running it through rubocop to auto fix style issues.
