### ISSUE TITLE
Doesn't output JSON for a very big YAML file

### ISSUE THREAD

**Issue by miparnisari** [binxio/serverless-cfnflip#4]
Tried to convert this large template: [limit_size.yaml](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/test/fixtures/templates/bad/limit_size.yaml)

It showed the loading animation for a while, and then nothing. However, `cfn-flip` outputs the right thing.

In the Chrome dev tools I see `{"message": "Internal server error"}`

**Comment by dennisvink** [comment]
Hi,

I've resolved the issue. This unusually big template put a strain on the capacity I had granted the Lambda function. As such, the Lambda timed out before it finished processing.

I've increased memory and CPU. It still takes a couple of seconds, but it now converts fine.
